# Generated by Django 4.2.7 on 2023-11-30 16:34

from django.db import migrations, models
import todolist_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255, validators=[todolist_app.validators.validate_list_name])),
            ],
        ),
    ]
